[package]
name = "compiler"
version = "0.1.0"
authors = ["QiuYuanhui <qiuyh0924@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
llvmgen = { path = "../llvmgen" }
cparser = { path = "../cparser" }
